### PR TITLE
Goal priority front

### PR DESCRIPTION
**Pull request by MaksymilianK**

### CODE REVIEW

**Comment by elacymerys** [comment]
I'm not sure why, but when I create goals being logged in to one account then I can't create any goal being logged in to another account. I get a 'Goal conflict' error on snack bar ;-/

**Comment by elacymerys** [comment]
What's more, the goals on the list can be rearranged for a while, but then they return to their place when you try to change the order

**Comment by MaksymilianK** [comment]
> I'm not sure why, but when I create goals being logged in to one account then I can't create any goal being logged in to another account. I get a 'Goal conflict' error on snack bar ;-/

Ah, yes. This happens because of a wrong unique constraint in database. I fixed it and these changes are already merged into master. If you run backend from master branch, everything should work fine.

**Comment by MaksymilianK** [comment]
> What's more, the goals on the list can be rearranged for a while, but then they return to their place when you try to change the order

Does this still happen when you run backend from master branch?

**Comment by elacymerys** [comment]
Since this is one repo holding frontend and backend I think I can't run front on this branch and backend on master branch ;-/
I'll merge them to check if it works and let you know

**Review by elacymerys — APPROVED** [review]

**Comment by elacymerys** [comment]
Ok, I approved and merged it

**Comment by elacymerys** [comment]
Now the second issue is resolved but the first one is still not working. When I try to create a goal on other account, I get 'Goal conflict' error ;-/

**Comment by elacymerys** [comment]
Ok, it works ;-)

**Pull request merged**
