### PR TITLE
Create event update form

### PR DESCRIPTION
**Pull request by elacymerys**

### CODE REVIEW

**Review by MaksymilianK — CHANGES_REQUESTED** [review]
List items are expanding when clicking on update form. Attached file shows this strange effect.

https://user-images.githubusercontent.com/22754636/167020412-e34a2bff-6720-41ce-bc95-a594a5837a80.mp4

.

**Comment by elacymerys** [comment]
Yes, I'm aware of that but hence each list item must be a button, I don't know a method to change it ;-/

**Comment by MaksymilianK** [comment]
ok

**Review by MaksymilianK — APPROVED** [review]

**Comment by elacymerys** [comment]
Also when deleting an event, we also observe this effect ;-/
We can try to solve this but maybe during next sprint

**Pull request merged**
